name: Benchmark
on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - '.github/workflows/benchmark.yml'
      - 'src/**'
      - 'tests/**'
  workflow_dispatch:

permissions:
  contents: read

env:
  CARGO_REGISTRIES_CRATES_IO_PROTOCOL: sparse

jobs:
  benchmark:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        timeout-minutes: 3
      - name: Clone test vectors
        timeout-minutes: 2
        uses: ./.github/actions/fetch-vectors

      - name: Setup python
        id: setup-python
        uses: actions/setup-python@39cd14951b08e74b54015e9e001cdefcf80e669f # v5.1.1
        with:
          python-version: "3.12"

      - name: Create virtualenv
        run: |
          python -m venv .venv
          .venv/bin/pip install -v -c ./ci-constraints-requirements.txt "./[test]" ./vectors/

      - name: Run benchmarks
        uses: CodSpeedHQ/action@v2
        with:
          token: ${{ secrets.CODSPEED_TOKEN }}
          run: .venv/bin/pytest --codspeed --benchmark-enable --benchmark-only ./tests/bench/ --benchmark-json=bench-pr.json --x509-limbo-root=x509-limbo/
